# Mastering Pandas for Data Analysis: A Comprehensive Guide

# What is Pandas?

Pandas is a powerful open-source Python library used for data manipulation, data cleaning, and data analysis.

Built on top of NumPy, it allows for fast operations on tabular data (data in tables), like spreadsheets or SQL tables.

## Pandas Core Data Structures

### 1. Series

A one-dimensional labeled array capable of holding any data type.

In [276]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

### Key Features:

- Automatically assigns labels (indices) unless specified.

- Can hold any data type (int, float, str, etc.)

### 2. DataFrame

A two-dimensional labeled data structure (like a table in Excel or a database).

In [277]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Lagos', 'Abuja', 'Ibadan']
}
dfs = pd.DataFrame(data)
print(dfs)

      Name  Age    City
0    Alice   25   Lagos
1      Bob   30   Abuja
2  Charlie   35  Ibadan

### Key Features:

- Think of it like a dictionary of Series.

- Labeled rows (index) and columns.

## Creating DataFrames

In [278]:
# From a dictionary:

pd.DataFrame({'A': [1, 2], 'B': [3, 4]})

   A  B
0  1  3
1  2  4

In [279]:
# From a list of lists:

pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])

   A  B
0  1  2
1  3  4

In [280]:
# From a CSV file:

df = pd.read_csv('sales.csv')

## DataFrame Basic Operations

In [281]:
df.head()  # first 5 rows

   sale_id  product_id  employee_id   sale_date  quantity_sold  total_price
0        1           3            2  2023-03-01              3         1993
1        2           4            2  2023-03-11              9          912
2        3           4            3  2023-03-21              3          940
3        4           1            1  2023-03-31              5          963
4        5           1            2  2023-04-10              8          490

In [282]:
df.tail()  # last 5 rows

    sale_id  product_id  employee_id   sale_date  quantity_sold  total_price
15       16           2            2  2023-07-29              9          221
16       17           3            1  2023-08-08              4         1289
17       18           3            5  2023-08-18              7          644
18       19           5            5  2023-08-28              9          728
19       20           4            3  2023-09-07              6         1552

In [283]:
df.info()   # summary info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sale_id        20 non-null     int64
 1   product_id     20 non-null     int64
 2   employee_id    20 non-null     int64
 3   sale_date      20 non-null     object
 4   quantity_sold  20 non-null     int64
 5   total_price    20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

In [284]:
df.describe()  # statistical summary

        sale_id  product_id  employee_id  quantity_sold  total_price
count  20.00000   20.000000    20.000000      20.000000    20.000000
mean   10.50000    3.200000     2.900000       5.550000   984.500000
std     5.91608    1.361114     1.333772       2.723678   483.480202
min     1.00000    1.000000     1.000000       1.000000   221.000000
25%     5.75000    2.750000     2.000000       3.750000   698.750000
50%    10.50000    3.500000     2.500000       5.500000   926.000000
75%    15.25000    4.000000     4.000000       7.250000  1297.000000
max    20.00000    5.000000     5.000000       9.000000  1993.000000

In [285]:
# 1. Viewing Data

df.head(5)      
df.tail()      
df.info()      
df.describe()  # statistical summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sale_id        20 non-null     int64
 1   product_id     20 non-null     int64
 2   employee_id    20 non-null     int64
 3   sale_date      20 non-null     object
 4   quantity_sold  20 non-null     int64
 5   total_price    20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

        sale_id  product_id  employee_id  quantity_sold  total_price
count  20.00000   20.000000    20.000000      20.000000    20.000000
mean   10.50000    3.200000     2.900000       5.550000   984.500000
std     5.91608    1.361114     1.333772       2.723678   483.480202
min     1.00000    1.000000     1.000000       1.000000   221.000000
25%     5.75000    2.750000     2.000000       3.750000   698.750000
50%    10.50000    3.500000     2.500000       5.500000   926.000000
75%    15.25000    4.000000     4.000000       7.250000  1297.000000
max    20.00000    5.000000     5.000000       9.000000  1993.000000

# 2. Accessing Columns and Rows

In [286]:
df['total_price']         # Access column

0     1993
1      912
2      940
3      963
4      490
5      717
6      903
7     1094
8     1321
9     1506
10     332
11     765
12    1829
13     417
14    1074
15     221
16    1289
17     644
18     728
19    1552
Name: total_price, dtype: int64

In [287]:
df[['product_id', 'quantity_sold']]  # Multiple columns

    product_id  quantity_sold
0            3              3
1            4              9
2            4              3
3            1              5
4            1              8
5            4              9
6            1              7
7            3              7
8            1              1
9            3              5
10           4              1
11           5              1
12           5              5
13           4              5
14           4              7
15           2              9
16           3              4
17           3              7
18           5              9
19           4              6

In [288]:
df.iloc[0]         # First row (by position)

sale_id                   1
product_id                3
employee_id               2
sale_date        2023-03-01
quantity_sold             3
total_price            1993
Name: 0, dtype: object

In [289]:
df.loc[0]    # First row by label and index

sale_id                   1
product_id                3
employee_id               2
sale_date        2023-03-01
quantity_sold             3
total_price            1993
Name: 0, dtype: object

In [290]:
# 3. Filtering

df[df['quantity_sold'] > 5]

    sale_id  product_id  employee_id   sale_date  quantity_sold  total_price
1         2           4            2  2023-03-11              9          912
4         5           1            2  2023-04-10              8          490
5         6           4            3  2023-04-20              9          717
6         7           1            4  2023-04-30              7          903
7         8           3            4  2023-05-10              7         1094
14       15           4            2  2023-07-19              7         1074
15       16           2            2  2023-07-29              9          221
17       18           3            5  2023-08-18              7          644
18       19           5            5  2023-08-28              9          728
19       20           4            3  2023-09-07              6         1552

## Data Cleaning with Pandas

## Handling Missing Data

In [291]:
df.isnull().sum()              # Count missing

sale_id          0
product_id       0
employee_id      0
sale_date        0
quantity_sold    0
total_price      0
dtype: int64

In [292]:
df.fillna(0)                   # Fill with 0

    sale_id  product_id  employee_id   sale_date  quantity_sold  total_price
0         1           3            2  2023-03-01              3         1993
1         2           4            2  2023-03-11              9          912
2         3           4            3  2023-03-21              3          940
3         4           1            1  2023-03-31              5          963
4         5           1            2  2023-04-10              8          490
5         6           4            3  2023-04-20              9          717
6         7           1            4  2023-04-30              7          903
7         8           3            4  2023-05-10              7         1094
8         9           1            3  2023-05-20              1         1321
9        10           3            2  2023-05-30              5         1506
10       11           4            5  2023-06-09              1          332
11       12           5            5  2023-06-19              1          765
12       13           5            2  2023-06-29              5         1829
13       14           4            2  2023-07-09              5          417
14       15           4            2  2023-07-19              7         1074
15       16           2            2  2023-07-29              9          221
16       17           3            1  2023-08-08              4         1289
17       18           3            5  2023-08-18              7          644
18       19           5            5  2023-08-28              9          728
19       20           4            3  2023-09-07              6         1552

In [293]:
df.dropna()                    # Drop missing rows

    sale_id  product_id  employee_id   sale_date  quantity_sold  total_price
0         1           3            2  2023-03-01              3         1993
1         2           4            2  2023-03-11              9          912
2         3           4            3  2023-03-21              3          940
3         4           1            1  2023-03-31              5          963
4         5           1            2  2023-04-10              8          490
5         6           4            3  2023-04-20              9          717
6         7           1            4  2023-04-30              7          903
7         8           3            4  2023-05-10              7         1094
8         9           1            3  2023-05-20              1         1321
9        10           3            2  2023-05-30              5         1506
10       11           4            5  2023-06-09              1          332
11       12           5            5  2023-06-19              1          765
12       13           5            2  2023-06-29              5         1829
13       14           4            2  2023-07-09              5          417
14       15           4            2  2023-07-19              7         1074
15       16           2            2  2023-07-29              9          221
16       17           3            1  2023-08-08              4         1289
17       18           3            5  2023-08-18              7          644
18       19           5            5  2023-08-28              9          728
19       20           4            3  2023-09-07              6         1552

In [294]:
# renaming the Name column
df.rename(columns={'quantity_sold': 'number_of_quantity_sold'}, inplace=True)
df

,sale_id,product_id,employee_id,sale_date,number_of_quantity_sold,total_price
0,1,3,2,2023-03-01,3,1993
1,2,4,2,2023-03-11,9,912
2,3,4,3,2023-03-21,3,940
3,4,1,1,2023-03-31,5,963
4,5,1,2,2023-04-10,8,490
5,6,4,3,2023-04-20,9,717
6,7,1,4,2023-04-30,7,903
7,8,3,4,2023-05-10,7,1094
8,9,1,3,2023-05-20,1,1321
9,10,3,2,2023-05-30,5,1506
10,11,4,5,2023-06-09,1,332
11,12,5,5,2023-06-19,1,765
12,13,5,2,2023-06-29,5,1829
13,14,4,2,2023-07-09,5,417
14,15,4,2,2023-07-19,7,1074
15,16,2,2,2023-07-29,9,221
16,17,3,1,2023-08-08,4,1289
17,18,3,5,2023-08-18,7,644
18,19,5,5,2023-08-28,9,728
19,20,4,3,2023-09-07,6,1552

In [295]:
# 2. Renaming Columns

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Lagos', 'Abuja', 'Ibadan']
}
df = pd.DataFrame(data)
df

      Name  Age    City
0    Alice   25   Lagos
1      Bob   30   Abuja
2  Charlie   35  Ibadan

In [296]:
# renaming the Name column
df.rename(columns={'Name': 'FullName'}, inplace=True)

# Printing the updated DataFrame
print(df)

  FullName  Age    City
0    Alice   25   Lagos
1      Bob   30   Abuja
2  Charlie   35  Ibadan

In [297]:
# 3. Changing Data Types

df['Age'] = df['Age'].astype(float)

## DataFrame Operations

In [298]:
# 1. Adding New Columns

df['Salary'] = [5000, 6000, 7000]

In [299]:
# 2. Applying Functions

df['AgePlusTen'] = df['Age'].apply(lambda x: x + 10)

In [300]:
# 3. Sorting

df.sort_values('Age', ascending=False)

  FullName   Age    City  Salary  AgePlusTen
2  Charlie  35.0  Ibadan    7000        45.0
1      Bob  30.0   Abuja    6000        40.0
0    Alice  25.0   Lagos    5000        35.0

## Combining DataFrames

In [301]:
# 1. Concatenation

# First DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

# Second DataFrame
df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['David', 'Emma', 'Frank'],
    'Age': [28, 32, 29]
})

# Joining them together - Concatenation
pd.concat([df1, df2])

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
0   4    David   28
1   5     Emma   32
2   6    Frank   29

In [302]:
# For merge to work, we need matching IDs.

# Use this instead:

# New DataFrame for merging

df3 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Department': ['Sales', 'IT', 'Finance']
})

df3

   ID Department
0   1      Sales
1   2         IT
2   3    Finance

In [303]:
# 2. Merging (like SQL join)

pd.merge(df1, df3, on='ID', how='inner')

   ID     Name  Age Department
0   1    Alice   25      Sales
1   2      Bob   30         IT
2   3  Charlie   35    Finance

In [304]:
# 3. Joining

df1.join(df2, how='outer')

ValueError: columns overlap but no suffix specified: Index(['ID', 'Name', 'Age'], dtype='object')

## GroupBy and Aggregations

In [ ]:
df.groupby('City')['Age'].mean()

City
Abuja     30.0
Ibadan    35.0
Lagos     25.0
Name: Age, dtype: float64

Common aggregation functions:

- sum()

- mean()

- count()

- min()

- max()

## Pivot Tables

In [ ]:
df.pivot_table(index='City', columns='Gender', values='Salary', aggfunc='mean')

## Reshaping and Melting

In [ ]:
# Reshape:

df.pivot(index='Name', columns='City', values='Salary')

In [ ]:
# Melt:

pd.melt(df, id_vars=['Name'], value_vars=['Salary', 'Age'])

## Read:

**pd.read_csv()**

**pd.read_excel()**

**pd.read_json()**

## Write:

**df.to_csv('filename.csv')**

**df.to_excel('filename.xlsx')**